/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author asus
 */
public class frame2 extends javax.swing.JFrame {

    /**
     * Creates new form frame2
     */
    public frame2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        CoOren = new javax.swing.JButton();
        CeOren = new javax.swing.JButton();
        CoBiru = new javax.swing.JButton();
        CeBiru = new javax.swing.JButton();
        CoIjo = new javax.swing.JButton();
        CeIjo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 204));
        jLabel7.setText("PILIH KARAKTERMU");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(139, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 510, 60);

        jPanel3.setLayout(null);

        CoOren.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rfergr.png"))); // NOI18N
        CoOren.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CoOrenActionPerformed(evt);
            }
        });
        jPanel3.add(CoOren);
        CoOren.setBounds(10, 10, 110, 120);

        CeOren.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cecev.png"))); // NOI18N
        CeOren.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CeOrenActionPerformed(evt);
            }
        });
        jPanel3.add(CeOren);
        CeOren.setBounds(120, 10, 110, 120);

        CoBiru.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbtgbgb.png"))); // NOI18N
        CoBiru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CoBiruActionPerformed(evt);
            }
        });
        jPanel3.add(CoBiru);
        CoBiru.setBounds(280, 10, 110, 120);

        CeBiru.setIcon(new javax.swing.ImageIcon(getClass().getResource("/egtgteh.png"))); // NOI18N
        CeBiru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CeBiruActionPerformed(evt);
            }
        });
        jPanel3.add(CeBiru);
        CeBiru.setBounds(390, 10, 110, 120);

        CoIjo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co.png"))); // NOI18N
        CoIjo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CoIjoActionPerformed(evt);
            }
        });
        jPanel3.add(CoIjo);
        CoIjo.setBounds(150, 150, 110, 120);

        CeIjo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/peras otakcew.png"))); // NOI18N
        CeIjo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CeIjoActionPerformed(evt);
            }
        });
        jPanel3.add(CeIjo);
        CeIjo.setBounds(260, 150, 110, 120);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(0, 60, 510, 290);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CoBiruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CoBiruActionPerformed
        // TODO add your handling code here:
        frame3 tiga = new frame3();
        tiga.show();
        dispose();
    }//GEN-LAST:event_CoBiruActionPerformed

    private void CoOrenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CoOrenActionPerformed
        // TODO add your handling code here:
        frame3 tiga = new frame3();
        tiga.show();
        dispose();
    }//GEN-LAST:event_CoOrenActionPerformed

    private void CeOrenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CeOrenActionPerformed
        // TODO add your handling code here:
        frame3 tiga = new frame3();
        tiga.show();
        dispose();
    }//GEN-LAST:event_CeOrenActionPerformed

    private void CeBiruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CeBiruActionPerformed
        // TODO add your handling code here:
        frame3 tiga = new frame3();
        tiga.show();
        dispose();
    }//GEN-LAST:event_CeBiruActionPerformed

    private void CoIjoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CoIjoActionPerformed
        // TODO add your handling code here:
        frame3 tiga = new frame3();
        tiga.show();
        dispose();
    }//GEN-LAST:event_CoIjoActionPerformed

    private void CeIjoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CeIjoActionPerformed
        // TODO add your handling code here:
        frame3 tiga = new frame3();
        tiga.show();
        dispose();
    }//GEN-LAST:event_CeIjoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frame2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CeBiru;
    private javax.swing.JButton CeIjo;
    private javax.swing.JButton CeOren;
    private javax.swing.JButton CoBiru;
    private javax.swing.JButton CoIjo;
    private javax.swing.JButton CoOren;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
